package com.myspace.logistics;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Order implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String merchant;
	private java.lang.Double weight;
	private java.lang.Boolean expedited;
	private java.lang.String destination;

	public Order() {
	}

	public java.lang.String getMerchant() {
		return this.merchant;
	}

	public void setMerchant(java.lang.String merchant) {
		this.merchant = merchant;
	}

	public java.lang.Double getWeight() {
		return this.weight;
	}

	public void setWeight(java.lang.Double weight) {
		this.weight = weight;
	}

	public java.lang.Boolean getExpedited() {
		return this.expedited;
	}

	public void setExpedited(java.lang.Boolean expedited) {
		this.expedited = expedited;
	}

	public java.lang.String getDestination() {
		return this.destination;
	}

	public void setDestination(java.lang.String destination) {
		this.destination = destination;
	}

	public Order(java.lang.String merchant, java.lang.Double weight,
			java.lang.Boolean expedited, java.lang.String destination) {
		this.merchant = merchant;
		this.weight = weight;
		this.expedited = expedited;
		this.destination = destination;
	}

}